-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Dec 09, 2022 at 05:32 PM
-- Server version: 5.7.34
-- PHP Version: 7.4.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `local_idm232_01`
--

-- --------------------------------------------------------

--
-- Table structure for table `therapists`
--

CREATE TABLE `therapists` (
  `id` int(11) NOT NULL,
  `therapist_name` varchar(255) NOT NULL,
  `therapist_job` varchar(255) NOT NULL,
  `therapist_pronoun` varchar(255) NOT NULL,
  `therapist_email` varchar(255) NOT NULL,
  `therapist_phone` varchar(255) NOT NULL,
  `therapist_about` longtext NOT NULL,
  `therapist_specialties` longtext NOT NULL,
  `therapist_issues` longtext NOT NULL,
  `image_path` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `therapists`
--

INSERT INTO `therapists` (`id`, `therapist_name`, `therapist_job`, `therapist_pronoun`, `therapist_email`, `therapist_phone`, `therapist_about`, `therapist_specialties`, `therapist_issues`, `image_path`) VALUES
(30, 'Jotie Mondair', 'Licensed Professional Counselor, PA. LPC, ATR-BC', 'She / Her / Hers', 'Jotie.Mondair@psychologytoday.com', '(215) 974 - 0190', '<p>Jotie is a licensed professional counselor located in Philadelphia, Pennsylvania with many years of experience working with depression, anxiety, eating disorders, and trauma-related disorders. Jotie uses an attachment-based model to identify and address distorted thought patterns and improve relationships (between people, with themselves, or with food).</p>\r\n<p>&nbsp;</p>\r\n<p>Seeking help can be a difficult and scary process. Please know that you are not alone in this journey. Reach out whenever you are ready.</p>\r\n<p>&nbsp;</p>\r\n<p>Please note: if this is a medical or psychiatric emergency, call 9-1-1 for support.</p>', '<ul>\r\n<li>Eating Disorders</li>\r\n<li>Depression&nbsp;</li>\r\n<li>Trauma and PTSD</li>\r\n</ul>', '<ul>\r\n<li>Acculturation</li>\r\n<li>Anxiety&nbsp;</li>\r\n<li>Coping Skills&nbsp;</li>\r\n<li>Family Conflict&nbsp;</li>\r\n<li>Grief&nbsp;</li>\r\n<li>Life Transitions</li>\r\n<li>Parenting&nbsp;</li>\r\n<li>Self Esteem&nbsp;</li>\r\n<li>Self-Harming&nbsp;</li>\r\n<li>Stress&nbsp;</li>\r\n<li>Suicidal Ideation&nbsp;</li>\r\n<li>Women\'s Issues</li>\r\n</ul>', '/dist/images/therapist2.jpeg'),
(34, 'Colleen Keller', 'Clinical Social Work / Therapist, LCSW', 'She / Her / Hers', 'Colleen.Keller@psychologytoday.com', '(267) 489 - 2617', '<p>Are you feeling tired and overwhelmed by all that is going on in your life right now? Maybe you feel like you have too many balls in the air or that something in your life is just not working as well as it could be. Are you anxious or fearful of not making the right decision in your personal and/or professional life? You want help with it all, but you don\'t even know where to begin. If so, you don&rsquo;t have to shoulder these burdens on your own. I will help you take a breath, step back, and look at what\'s working well in your life and what we can work on together to make better.</p>\r\n<p>&nbsp;</p>\r\n<p>As a Cognitive Behavioral Therapist (CBT), I am able to see connections between your feelings, thoughts, and behaviors. I will help you identify the thoughts and behaviors holding you back and together we will work to create positive connections. This therapy works well with those struggling with anxiety, depression, panic attacks, anger issues, and phobias.</p>\r\n<p>&nbsp;</p>\r\n<p>I know beginning therapy can feel daunting and it\'s normal to feel reluctant. I am happy to offer a free 15-minute consultation to talk with you and see if I may be able to help. Feel free to reach me via email for the quickest response. You are valuable, you deserve to be happy, and you are worth investing in your well-being!</p>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Pregnancy</li>\r\n<li>Prenatal</li>\r\n<li>Postpartum</li>\r\n<li>Women\'s Issues</li>\r\n</ul>', '<ul>\r\n<li>Alcohol Use</li>\r\n<li>Marital and Premarital</li>\r\n<li>Depression</li>\r\n<li>Relationships</li>\r\n<li>Life Transitions</li>\r\n<li>Stress</li>\r\n<li>Trauma and PTSD</li>\r\n</ul>', '/dist/images/therapist5.jpeg'),
(35, 'Natashja Rinaldo-James', 'Licensed Professional Counselor, BSSW, MS, LPC, RYT', 'She / Her / Hers', 'Natashja.R.James@psychologytoday.com', '(123) 456 - 7890', '<p>If you are a mental health professional looking to elevate your career, I\'ve got you! I am offering both individual and group supervision sessions for those seeking their LPC in the state of Pennsylvania. I have a specific interest in supervising counselors of color.</p>\r\n<p>&nbsp;</p>\r\n<p>As a BIPOC and ally to the LGBTQIA+ community, I am a clinician who is both inclusive and trauma-conscious. Primarily, my experience has been with young adults, teens, tweens and parents in a variety of mental health and academic settings. I also have specialties in social work, special education, secondary school/college counseling, and yoga/mindfulness.</p>\r\n<p>&nbsp;</p>\r\n<p>If you are interested in learning more, please e-mail me for a FREE 30-minute consultation. When choosing a supervisor, it\'s so important that the two of you are a good match. Let\'s connect and see how we can work together to achieve your professional goals.</p>', '<ul>\r\n<li>Career Counseling</li>\r\n<li>School Issues</li>\r\n<li>Trauma and PTSD</li>\r\n</ul>', '<ul>\r\n<li>Anxiety</li>\r\n<li>ADHA</li>\r\n<li>Education and Learning Disabilities</li>\r\n<li>Emotional Disturbance</li>\r\n<li>Racial Identity</li>\r\n<li>Sexual Abuse</li>\r\n<li>Sleep or Insomnia</li>\r\n<li>Suicidal Evaluation</li>\r\n<li>Transgender Teen Violence</li>\r\n</ul>', '/dist/images/therapist6.jpeg'),
(37, 'Lawrence Peers', 'Pre-Licensed Professional, MA, CAGS, PCC', 'He / Him / His', 'Lawrence.Peers@psychologytoday.com', '(267) 772 - 5650', '<p>I help a wide range of clients: those seeking personal growth as well as those moving through depression, anxiety, betrayal, grief, career and life transitions or interpersonal tensions or conflicts. I assist individuals, couples and leaders during times of conflict or life/career transition to move with intention toward new possibilities. When a client is feeling stuck or struggling to pay attention to \"what matters most\", we work in a collaborative way to recognize underlying obstacles to their well-being and identify practical actions to move them forward.&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>I use an integral approach incorporating Mindfulness Acceptance &amp; Commitment Therapy, Somatic Psychotherapy, Narrative Therapy and Psychosynthesis. When indicated, I support my clients with Open Focus&reg; Attention Training, Coaching Psychology and HeartMath&reg;. As a Professional Certified Coach, I tend to do therapy with \"a coaching edge.\"</p>\r\n<p>&nbsp;</p>\r\n<p>Please contact me if you feel you would benefit from a collaborative approach to therapy that helps you to hone your deep inner resources, access the wisdom of your body and your heart, and turn your insights into practical next steps.</p>', '<ul>\r\n<li>Life Transitions</li>\r\n<li>Career Counseling</li>\r\n<li>Stress</li>\r\n</ul>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Attention and Focus</li>\r\n<li>Family Conflict</li>\r\n<li>Life Couching</li>\r\n<li>Men\'s Issues</li>\r\n<li>Spirituality</li>\r\n</ul>', '/dist/images/therapist7.jpeg'),
(38, 'Amber Teachen', 'Marriage and Family Therapist, LMFT', 'She / Her / Hers', 'Amber.Teachen@psychologytoday.com', '(267) 494 - 0952', '<p>Do you struggle with feeling confident? Do you feel like you need to please others? Does it feel hard to manage emotional reactions? Or maybe you\'re a parent stressed and overwhelmed from finding the best way to support your child/teen? Do you get into power struggles at home? I am a Licensed Marriage and Family Therapist providing relational, systemic-oriented, and collaborative individual and family services to children, teens, young adults, and parents. In the course of our lives, we each get stuck in patterns and need help discovering what\'s keeping us from experiencing life in a way that feels healthy and happy.</p>\r\n<p>&nbsp;</p>\r\n<p>As a therapist, I collaborate with my clients to develop individualized goals, while focusing on their strengths and needs. I work with individuals on finding management strategies for anxiety, depression, stress, while also exploring the root of the issue. I also help families by supporting teens and parents struggling in their relationship with each other.</p>\r\n<p>&nbsp;</p>\r\n<p>Taking that first step towards therapy, or returning can often feel intimidating and scary. That is okay and normal. I\'m proud of you for looking to take this step! I offer a free 15 minute consultation to determine if we would be a good fit to work together. I look forward to connecting and getting to support you in this next step!</p>', '<ul>\r\n<li>Family Conflict</li>\r\n<li>Parenting</li>\r\n<li>Anxiety</li>\r\n</ul>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Child Aggression / Tantrum Behaviours</li>\r\n<li>Coping Skills</li>\r\n<li>Depression Martial and Premarital</li>\r\n<li>Stress</li>\r\n</ul>', '/dist/images/therapist8.jpeg'),
(39, 'Rodney Drafts', 'Clinical Social Work / Therapist, LCSW', 'He / They / Them', 'Rodney.Drafts@psychologytoday.com', '(215) 253 - 7461', '<p>I have over (25) years providing counseling services to individuals, couples and families.</p>\r\n<p>&nbsp;</p>\r\n<p>I am dedicated to providing quality services and enjoy seeing my clients achieve their goals.</p>\r\n<p>&nbsp;</p>\r\n<p>I&rsquo;m an active listener and provide therapeutic feedback to my clients. I view therapy as a step process to achieving desired goals!</p>', '<ul>\r\n<li>Eating Disorders</li>\r\n<li>Depression</li>\r\n<li>Couples Counseling</li>\r\n</ul>', '<ul>\r\n<li>Addiction</li>\r\n<li>Anger Management</li>\r\n<li>Coping Skills</li>\r\n<li>Men\'s Issues</li>\r\n<li>Spirituality</li>\r\n</ul>', '/dist/images/therapist9.jpeg'),
(40, 'Jaynay C. Johnson', 'Marriage and Family Therapist, LMFT', 'She / Her / Hers', 'Jaynay.C.Johnson@psychologytoday.com', '(267) 489 - 1241', '<p>If you found me, then I know you\'re doing your best to support your teenager or the teenager in your life through challenging circumstances. You\'ve found the right therapist to help you to support them. I\'m also going to help keep your teen navigate their experiences to learn skills to help them cope and manage their emotional wellness. With so many touchpoints, I believe it is critical to help teenagers create an informed decision-making self-compass to avoid self-inflicted harm, which can include self-mutilation, isolation, suicidal thoughts, and more.</p>\r\n<p>&nbsp;</p>\r\n<p>Teen Talk uses a teen-centered brief therapy approach, allowing teens to feel successful in treatment. Being a teen-centered clinician will enable teenagers to explore without an overwhelming sense of pressure from an authority figure. This ultimately allows the teen to come to their conclusions and renders the results every parent can feel safe with.</p>\r\n<p>&nbsp;</p>\r\n<p>Sessions at Teen Talk are just what you and your teen need on your journey to healthy living. Let\'s connect via email or phone to discuss how my partnership with your family can help your family get back to joy. Clinical case consultations are also available. I am also accepting MFT supervisee\'s.</p>', '<ul>\r\n<li>Suicidal Ideation</li>\r\n<li>Self-Harming</li>\r\n<li>Depression</li>\r\n</ul>', '<ul>\r\n<li>ADHA</li>\r\n<li>Anger Management</li>\r\n<li>Anxiety</li>\r\n<li>Child</li>\r\n<li>Parenting</li>\r\n<li>Self Esteem</li>\r\n<li>School Issues</li>\r\n<li>Life Transitions</li>\r\n</ul>', '/dist/images/therapist10.jpeg'),
(41, 'Peter Andrew Danzig', 'Clinical Social Work / Therapist, LSW, MSS, MA, CPT', 'They / Them ', 'Peter.Andrew.Danzig@psychologytoday.com', '(610) 632 - 1303', '<p>Peter Andrew Danzig is a Therapist, Creativity and Career Coach, and Diversity and Inclusion Consultant in the Greater Philadelphia region. Peter&rsquo;s research and practice interests are invested in community mental health, theories on adult play and the ways it frames our social interactions, and trauma informed work with clients and artists/creatives. Peter&rsquo;s clinical approach is rooted in holistic, relational and humanistic theory. He believes in a strengths-based perspective, recognizing the resiliency in his clients.</p>\r\n<p>&nbsp;</p>\r\n<p>He hopes to always create a supportive and safe space to help clients navigate trauma, conflict, and difficult life transitions with clear and focused goals. Peter passionately believes in the therapeutic relationship between therapist and client and strives to support his clients in a myriad of ways including talk therapy and creative therapy practices.</p>\r\n<p>&nbsp;</p>\r\n<p>Peter&rsquo;s practice focuses on the ways in which our minds and bodies are often separated through trauma and looks for healing approaches in which to strengthen our fragmented selves. His work primarily integrates person-centered and somatic based approaches to mental health while also utilizing various therapeutic techniques to support his client\'s healing.</p>', '<ul>\r\n<li>Mood Disorders</li>\r\n<li>Anxiety</li>\r\n<li>Trauma and PTSD</li>\r\n</ul>', '<ul>\r\n<li>Anxiety</li>\r\n<li>ADHA</li>\r\n<li>Alcohol Use</li>\r\n<li>Anger Management</li>\r\n<li>Dual Diagnosis</li>\r\n<li>Drug Borderline Personality (BPD)</li>\r\n<li>Internet Addition</li>\r\n<li>Infidelity</li>\r\n<li>Substance Use</li>\r\n<li>Weight Loss</li>\r\n</ul>', '/dist/images/therapist11.jpeg'),
(42, 'Dr. Abe Zubarev', 'Clinical Social Work / Therapist, LCSW, BCD, ATR-BC, DPS', 'He / Him / His', 'Dr.Abe.Zubarev@psychologytoday.com', '(484) 978 - 8948', '<p>My goal is to offer high-quality teletherapy that is respectful, honest, supportive and collaborative. That means developing rapport so that you feel heard and comfortable to explore feelings and decisions without judgment. I work with male clients who want to live happier, healthier and more fulfilling lives. Specialties include gay men&rsquo;s issues, low self-esteem and loneliness, existential concerns, anxiety/depression, and helping people on the autism spectrum.</p>\r\n<p>&nbsp;</p>\r\n<p>Believing in the therapeutic process means that I develop a rapport with my clients so that they feel heard and comfortable to explore their feelings and decisions without judgment. My specialties include low self-esteem/perfectionism and loneliness, career counseling, existential concerns, gay men&rsquo;s issues, social anxiety, and helping people on the spectrum.</p>', '<ul>\r\n<li>Self Esteem</li>\r\n<li>Men\'s Issues</li>\r\n<li>Asperger\'s Syndrome</li>\r\n</ul>', '<ul>\r\n<li>Adolescents &amp; Young Adults; College Students</li>\r\n<li>Anxiety</li>\r\n<li>Autism</li>\r\n<li>Career</li>\r\n<li>Counseling</li>\r\n<li>Coping Skills</li>\r\n<li>Depression</li>\r\n<li>Graduate Students</li>\r\n<li>Life Transitions</li>\r\n<li>Stress</li>\r\n</ul>', '/dist/images/therapist12.jpeg'),
(43, 'Lori O\'Mara', 'Clinical Social Work / Therapist, LCSW, CST', 'They / Them ', 'Lori.O\'Mara@psychologytoday.com', '(267) 429 - 4804', '<p>YOU are capable of creating change in your life. My role is one of encouragement and support for making that change. Together we will find ways to cope better in the situations that matter to you and facilitate personal growth by exploring new ways to interact with your world and the people in it. I believe you are the best resource on what works for you. Sometimes, though, we all need a little support and encouragement to make the necessary changes to create/restore balance and calm the inner turbulence.&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>I am a Licensed Clinical Social Worker and AASECT Certified Sex Therapist. Areas of specialty include: infertility, sexual interest/arousal disorders, women\'s health (pelvic pain/penetration and arousal disorders), consensual non-monogamy, polyamory, anxiety, depression, life transitions, entrepreneurial coaching, and stress management.&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>I would love to work with you. In session, I draw Cognitive Behavioral Therapy, Family Systems Therapy, EFT (tapping) and somatic/psychodynamic approaches to therapy. At Cope Better Therapy we create customized treatment plans to fit your needs and lifestyle. Due to Covid all sessions are remote at this time.</p>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Infertility</li>\r\n<li>Sex Therapy</li>\r\n</ul>', '<ul>\r\n<li>Cancer Support and Entrepreneurial Couching</li>\r\n<li>Career Counseling</li>\r\n<li>Chronic Illness</li>\r\n<li>Chronic Pain</li>\r\n<li>Coping Skills</li>\r\n<li>Depression</li>\r\n<li>Grief</li>\r\n<li>Life Coaching</li>\r\n<li>Life Transitions</li>\r\n<li>Peer Transitions</li>\r\n<li>Relationship Issues</li>\r\n<li>Sexual Interest / Arousal Disorder, Pelvic Pain</li>\r\n<li>Sleep or Insomnia</li>\r\n<li>Women\'s Issues</li>\r\n</ul>', '/dist/images/therapist13.jpeg'),
(44, 'Jonathan Lewis', 'Licensed Professional Counselor,  LPC', 'They / Them ', 'Jonathan.Lewis@psychologytoday.com', '(267) 209 - 6663', '<p>Jonathan Lewis is a Licensed Professional Counselor (LPC) who also holds a Master of Human Services Graduate Degree (MHS). Jonathan has over 15 years experience partnering with adults seeking help with depression, anxiety, life transitions, men&rsquo;s issues and relationship issues. He received his Master of Human Services Degree from historic Lincoln University. Jonathan utilizes relational, collaborative, strength based, cognitive behavioral, mindfulness based, solution focused and emotionally focused approaches to therapy always maintaining the creativity, flexibility and awareness necessary to best meet the needs of everyone.</p>\r\n<p>&nbsp;</p>\r\n<p>Jonathan seeks to establish a warm and caring relationship with you in order to assist in building on your strengths and better collaborate with you toward meeting your goals and living the meaningful life you value and desire.</p>\r\n<p>&nbsp;</p>\r\n<p>Aside from his experience and personal qualities, Jonathan\'s passion for change is at the core of his counseling. Jonathan is a firm believer that Human Beings have the capacity to change, and many of his clients can attest to that. Jonathan takes pride in providing care with openness and empathy, while providing balance and stability.</p>', '<ul>\r\n<li>Addiction</li>\r\n<li>Alcohol Use</li>\r\n<li>Grief</li>\r\n</ul>', '<ul>\r\n<li>Anger Management</li>\r\n<li>Depression</li>\r\n<li>Domestic Violence</li>\r\n<li>Gambling Men\'s Issues</li>\r\n<li>Stress</li>\r\n<li>Substance Use</li>\r\n<li>Trauma and PTSD</li>\r\n</ul>', '/dist/images/therapist14.jpeg'),
(45, 'Sherira J Fernandes', 'Psychologist, PhD, NCSP', 'She / Her / Hers', 'Sherira.J.Fernandes@psychologytoday.com', '(484) 209 - 2579', '<p>You feel like there&rsquo;s a rule book for life that you missed. You have an ADHD or Autism diagnosis, or maybe people tell you that you should, but what does that really mean? I can help you understand what this means for you; how your actions are impacting others, and how other people impact you. This might include working on planning, organization/ executive functioning, or working on personal goal setting/finding direction. Coaching will provide you with a safe place to be yourself, insight into your life, and concrete tips for moving forward, allowing you to be the best possible version of yourself. It\'s about you.</p>\r\n<p>&nbsp;</p>\r\n<p>With over a decade of experience, including the diagnosis and coaching of ADHD, autism, and learning differences, I take a strength-based approach to understanding your situation in context. We can do a full evaluation, or go straight into treatment. Let\'s not wait to get started!</p>\r\n<p>&nbsp;</p>\r\n<p>You don&rsquo;t have to do this alone. I&rsquo;ve helped countless families and individuals through challenges with ADHD and Autism and seen them thrive with a thorough, confidential evaluation, or treatment/coaching. Through our work together, we sift through all the noise, so that you can get down to what really matters &ndash; enjoying a happy and healthy life.</p>', '<ul>\r\n<li>Autism</li>\r\n<li>Testing and Evaluation</li>\r\n<li>ADHA</li>\r\n</ul>', '<ul>\r\n<li>Behavioral Issues</li>\r\n<li>Coping Skills</li>\r\n<li>Developmental Disorders</li>\r\n<li>Dual Diagnosis</li>\r\n<li>Education and Learning Disabilities</li>\r\n<li>Pregnancy, Prenatal, Postpartum</li>\r\n<li>School Issues</li>\r\n</ul>', '/dist/images/therapist15.jpeg'),
(46, 'Sarah Amon', 'Clinical Social Work / Therapist, LMFT', 'They / Them ', 'Sarah.Amon@psychologytoday.com', '(267) 728 - 4643', '<p>Sarah Amon, LMFT Sarah Amon is a Licensed Marriage and Family Therapist in Pennsylvania who has been practicing since 2017. She graduated from Thomas Jefferson University. Sarah believes that people want to connect but struggle due to their past pains. She strives to be nonjudgmental, understanding, empathetic, and curious. Sarah will connect with a client\'s pain, stress, and fears while identifying their strengths. Holding a stance of collaboration will help the building of connection and foster moments of understanding. In her spare time, Sarah enjoys planting, sewing, origami, beauty services, and reading.</p>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Depression</li>\r\n</ul>', '<ul>\r\n<li>Autism</li>\r\n<li>Family Conflict</li>\r\n<li>Marital and Premarital</li>\r\n<li>Men\'s Issues</li>\r\n<li>Relationship Issues</li>\r\n<li>Women\'s Issues</li>\r\n</ul>', '/dist/images/therapist16.jpeg'),
(47, 'Madelena Tran', 'Pre-Licensed Professional', 'She / Her / Hers', 'Madelena.Tran@psychologytoday.com', '(484) 209 - 0431', '<p>Madelena Tran is a National Certified Counselor and Certified School Counselor. Madelena is currently a Resident Clinician and is working towards becoming a Licensed Professional Counselor. She has earned her Bachelor of Arts from Temple University with a degree in Communication Sciences &amp; Disorders and has earned a Master of Arts from Rider University in Counseling Services.</p>\r\n<p>&nbsp;</p>\r\n<p>Madelena utilizes Person-Centered, Strength Based, Mindfulness, and Cognitive Behavioral Therapy based approaches in working with her clients. She strongly believes meeting her clients where they are through their own self discovery. Madelena values the importance of creating a warm and non-judgmental environment.</p>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Depression</li>\r\n<li>Relationship Issues</li>\r\n</ul>', '<ul>\r\n<li>Self Esteem</li>\r\n<li>Trauma and PTSD</li>\r\n<li>Stress</li>\r\n</ul>', '/dist/images/therapist17.jpeg'),
(48, 'Eva Chen', 'LPC Intern', 'She / Her / Hers', 'Eva.Chen@psychologytoday.com', '(484) 804 - 4347', '<p>Sometimes it\'s really not easy to walk your journey on your own, especially when you have something weighing on your mind and shoulders. I feel you. I view my mission as joining your walk and help you regain hope, find your goals and resources, and reach your desired destination. I value your autonomy and believe in the power of teamwork. I will provide a safe, secure, and warm space for vulnerability and genuine conversations. I welcome authenticity and always acknowledge your best interests.</p>\r\n<p>&nbsp;</p>\r\n<p>I utilize evidence-based techniques from CBT/DBT, EFT, Mindfulness, etc. in an integrative approach to adapt to your personal needs. I have a history working with children, adolescents, and young adults in public agency, private practice, and hospital settings.</p>\r\n<p>&nbsp;</p>\r\n<p>I\'m in my final year of study in the Counseling &amp; Human Services Masters&rsquo; program at Lehigh University, and I\'m currently working under the supervision of a Licensed Professional Counselor at MTR Therapy. I am able to provide virtual sessions to individuals in PA. To learn more or to schedule an appointment online, please go to our website, email, or call.</p>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Relationship Issues</li>\r\n<li>Life Transitions</li>\r\n</ul>', '<ul>\r\n<li>Adoption</li>\r\n<li>Coping Skills</li>\r\n<li>Depression</li>\r\n<li>Emotional Disturbance</li>\r\n<li>Family Conflict</li>\r\n<li>Grief</li>\r\n<li>Parenting Peer</li>\r\n<li>Relationships</li>\r\n<li>Racial Identity</li>\r\n<li>Self Esteem</li>\r\n<li>Sexual Abuse</li>\r\n<li>Sexual Addiction&nbsp;</li>\r\n<li>Spirituality</li>\r\n<li>Suicidal Ideation</li>\r\n<li>Trauma PTSD</li>\r\n<li>Women\'s Issues</li>\r\n</ul>', '/dist/images/therapist18.jpeg'),
(50, 'Leilei Duan', 'Clinical Social Work / Therapist, MSW, LCSW', 'She / Her / Hers', 'Leilei.Duan@psychologytoday.com', '(267) 714 - 5107', '<p>I specialize in neurobiology-informed psychotherapy to address anxiety, depression, trauma, stress, attachment issues, etc.. My approach is integrative and whole person wellbeing focused. Psychological issues closely interact with physical health issues, such as chronic illness/pain, energy deficiency, sleeping, memory loss, eating/weight issues, etc. In therapy, I will work with you on the interdependent issues from psychological, biological, and environmental aspects and help you gain insights of your mind, body, and experiences, and use practical strategies to obtain healing and improve your quality of life.</p>\r\n<p>&nbsp;</p>\r\n<p>I use an integrated clinical approach that combines emotional, biological, interpersonal, and cognitive dynamics with evidence-based practices, such as Cognitive Behavioral Therapy, Psychodynamic, Sensorimotor Psychotherapy, and Mindful-Based Stress Reduction to help you process and reduce emotional and physical stress and regain a balance of life.</p>\r\n<p>&nbsp;</p>\r\n<p>I have over 10 years of experience of working in both hospital and mental health outpatient settings. I have enjoyed working with individuals and families to help them achieve their wellbeing goals. If you need a psychotherapist who possesses a thorough understanding of the interconnections between mind, body, environment, and health, please contact me.</p>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Depression</li>\r\n<li>Trauma and PTSD</li>\r\n</ul>', '<ul>\r\n<li>ADHD</li>\r\n<li>Addiction</li>\r\n<li>Anger Management</li>\r\n<li>Asperger\'s Syndrome</li>\r\n<li>Behavioral Issues</li>\r\n<li>Bipolar Disorder</li>\r\n<li>Chronic Illness</li>\r\n<li>Developmental Disorders</li>\r\n<li>Dual Diagnosis</li>\r\n<li>Eating Disorders</li>\r\n<li>Emotional Disturbance</li>\r\n<li>Obsessive-Compulsive (OCD)</li>\r\n<li>Oppositional Defiance (ODD)</li>\r\n<li>Self-Harming</li>\r\n<li>Traumatic Brain Injury (TBI)</li>\r\n<li>Weight Loss</li>\r\n</ul>', '/dist/images/therapist19.jpeg'),
(51, 'Stephanie Manasse', 'Psychology, PhD', 'She / Her / Hers', 'Stephanie.Manasse@psychologytoday.com', '(215) 935 - 4775', '<p>I am a licensed clinical psychologist with years of experience delivering evidence-based treatments, with a special focus on eating and weight disorders in both adolescents and adults. I treat bulimia nervosa, binge eating disorder, and restrictive eating disorders, as well as help people meet their health goals (e.g., changing diet and physical activity).I also specialize in lifestyle modification interventions designed to help people live healthier lives by improving diet/eating, sleep, and exercise habits.</p>\r\n<p>&nbsp;</p>\r\n<p>I specialize in Cognitive Behavioral Therapy, Acceptance and Commitment Therapy, and specialized evidence-based treatments for eating disorders such as Cognitive Behavioral Therapy for Eating Disorders, Exposure-based Treatment, and Family-Based Treatment for adolescents.</p>\r\n<p>&nbsp;</p>\r\n<p>In my approach to therapy, I strive to balance what the research shows is effective with the unique experiences of every client. Therapy is personalized and skills-based; in our work together, we will clarify your long-term goals and values and build the skills to better align your behavior with these goals and values.</p>', '<ul>\r\n<li>Eating Disorders</li>\r\n<li>Weight Loss</li>\r\n</ul>', '<ul>\r\n<li>Coping Skills</li>\r\n</ul>', '/dist/images/therapist20.jpeg'),
(52, 'Ashley Annestedt', 'Clinical Social Work / Therapist, LCSW', 'She / Her / Hers', 'Ashley.Annestedt@psychologytoday.com', '(501) 365 - 8510', '<p>Perhaps you\'ve been struggling with complex OCD, a Body Focused Repetitive Behavior like Trichotillomania or Skin Picking, or a Tic disorder or Tourette and have been to numerous therapists that just don\'t seem to get it or provide the treatment you are looking for. Sound familiar? We want to help you get back to the big, beautiful life you deserve, and we have the expertise, training, and experience to help you get there. We are a team of therapists licensed to serve 20+ states who utilize practical evidence-based treatments to help you not just survive but thrive.</p>\r\n<p>&nbsp;</p>\r\n<p>We specialize in the treatment of OCD using ACT (Acceptance and Commitment Therapy) and ERP (Exposure and Response Prevention). We also treat Body Focused Repetitive Behaviors using the ComB model and Tic Disorders/Tourette using CBIT (Comprehensive Behavioral Intervention for Tics), using measures to track our progress every step of the way.</p>\r\n<p>&nbsp;</p>\r\n<p>Sometime the hardest thing to do is to just show up! Reaching out for help can be a scary, confusing, and overwhelming process and we want to make it as easy as possible for you. We are here for any questions you have and invite you to visit our website where we provide more information on our therapists and treatment approach.</p>', '<ul>\r\n<li>Obsessive Compulsive Disorder (OCD)</li>\r\n<li>Tic Disorders / Tourette</li>\r\n<li>Body Focused Repetitive Behaviours (Trich / SPD)</li>\r\n</ul>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Women\'s Issues</li>\r\n</ul>', '/dist/images/therapist1.jpeg'),
(53, 'Makkah Hayes', 'Licensed Professional Counselor, MS, LPC, NCC', 'She / Her / Hers', 'Makkah.Hayes@psychologytoday.com', '(215) 974 - 0843', '<p>Jotie is a licensed professional counselor located in Philadelphia, Pennsylvania with many years of experience working with depression, anxiety, eating disorders, and trauma-related disorders. Jotie uses an attachment-based model to identify and address distorted thought patterns and improve relationships (between people, with themselves, or with food).</p>\r\n<p>&nbsp;</p>\r\n<p>Seeking help can be a difficult and scary process. Please know that you are not alone in this journey. Reach out whenever you are ready.</p>\r\n<p>&nbsp;</p>\r\n<p>Please note: if this is a medical or psychiatric emergency, call 9-1-1 for support.</p>', '<ul>\r\n<li>Eating Disorders</li>\r\n<li>Depression</li>\r\n<li>Trauma and PTSD</li>\r\n</ul>', '<ul>\r\n<li>Anxiety</li>\r\n<li>Coping Skills</li>\r\n<li>Depression</li>\r\n<li>Self Esteem</li>\r\n<li>Stress</li>\r\n</ul>', '/dist/images/therapist3.jpeg'),
(54, 'Dr. Shanny Shmuel', 'Psychologist, PsyD', 'She / Her / Hers', 'Dr.Shanny.Shmuel@psychologytoday.com', '(484) 989 - 9716', '<p>I am passionate about collaborating with you to provide evidence-based treatment that meets your needs. I use a cognitive behavioral approach (CBT) with a systemic lens to always consider the context in which a person lives. I believe that individuals are shaped by their experiences, as well as their interactions with the significant people and systems in their lives, and we have to take that context into account when addressing your problems to create the change you want to see. I work with my clients to identify what\'s getting in the way of living the life you want and help you learn strategies to overcome those challenges.</p>\r\n<p>&nbsp;</p>\r\n<p>I have experience working with children, teens, and adults on a wide variety of issues. I particularly enjoy working with individuals and families affected by anxiety and/or ADHD. Together, we can create a plan that builds on your strengths to move you towards your goals.</p>\r\n<p>&nbsp;</p>\r\n<p>Therapy is a partnership that relies on both of us bringing our expertise into the room. You are the expert on your life- it is my role to apply the theory and techniques of treatment to best fit you. I aim to create a space you feel comfortable exploring your thoughts, feelings, and behaviors and am grateful to be a part of that process.</p>', '<ul>\r\n<li>ADHA</li>\r\n<li>Anxiety</li>\r\n<li>Parenting</li>\r\n</ul>', '<ul>\r\n<li>Behavioral Issues</li>\r\n<li>Coping Skills</li>\r\n<li>Depression</li>\r\n<li>Grief</li>\r\n<li>Family Conflict</li>\r\n<li>Sleep or Insomnia</li>\r\n<li>Stress</li>\r\n<li>Self Esteem</li>\r\n<li>Peer Relationships</li>\r\n</ul>', '/dist/images/therapist4.jpeg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `therapists`
--
ALTER TABLE `therapists`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `therapists`
--
ALTER TABLE `therapists`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=55;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
